CHMS/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()
from CHMS import views

from django.conf import settings

# ... your normal urlpatterns here




urlpatterns = patterns('',

    url(r'hospital/$', include('hospital.urls')),
    url(r'pharmacy/', include('pharmacy.urls',namespace='phar_app')),
    url(r'history/', include('history_records.urls',namespace='history_records')),
    url(r'app/', include('androidApp.urls',namespace='android_app')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^patient/',include('patient.urls',namespace='patient_app')),
    url(r'^$', views.firstpage , name = 'firstpage'),
    url(r'^SystemHomePage/',views.SystemHomePage,name='SystemHomePage'),
    url(r'^PatientSearch/',views.PatientSearch,name='PatientSearch'),
    url(r'^rec/',include('Receptionist.urls', namespace='rec_app')),
    url(r'^login_all/',views.login,name='login_all'),
    url(r'^logout/',views.logout,name='logout'),
    url(r'^medicine/', include('medicine.urls',namespace='medicine_app')), # pharmacy
    url(r'^reports/',views.get_reports,name='reports'),
    url(r'^physician/',include('physician.urls',namespace='doc_app')),
    url(r'^messages/', include('django_messages.urls')),
    
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

Receptionist/urls.py
__author__ = 'soheil'

from django.conf.urls import patterns, url
from .views import patient_list_view , delete_guardian, set_schedule_view,update_schedule_view,delete_schedule
from .views import patient_create_view, patient_update_view,detail,delete,allocate_ward_view,update_ward_view



urlpatterns = patterns('',
    url(r'^search/','Receptionist.views.search_rec',name='rec_search'),

    url(r'^$', patient_list_view, name='patients-list'),
    url(
        r'^create/$',
        patient_create_view,
        name='patients-create',
    ),
    # url(
    #     r'^delete/(?P<pk>[\w]+)/$',
    #     PatientDeleteView.as_view(),
    #     name='patients-delete',
    # ),
    # url(
    #     r'^update/(?P<pk>[\w]+)/$',
    #     patient_update_view,
    #     name='patients-update',
    # ),
    # url(
    #     r'^(?P<username>[\w]+)/$',
    #     PatientDetailView.as_view(),
    #     name='patients-detail',
    # ),
    url(
        r'^delete/(?P<username>[\w]+)/$',
        delete,
        name='patients-delete',
    ),
    url(
        r'^update/(?P<username>[\w]+)/$',
        patient_update_view,
        name='patients-update',
    ),
    url(
        r'^(?P<username>[\w]+)/$',
        detail,
        name='patients-detail',
    ),
        url(
        r'^allocate_ward/(?P<username>[\w]+)/$',
        allocate_ward_view,
        name='allocate-ward',
    ),
         url(
        r'^update_ward/(?P<username>[\w]+)/$',
        update_ward_view,
        name='update-ward',
    ),
        url(
        r'^delete_ward/(?P<username>[\w]+)/$',
        delete_guardian,
        name='delete-ward',
    ),

        url(
        r'^set_schedule/(?P<username>[\w]+)/$',
        set_schedule_view,
        name='set-schedule',
    ),
        url(
        r'^update_schedule/(?P<username>[\w]+)/$',
        update_schedule_view,
        name='update-schedule',
    ),
        url(
        r'^delete_schedule/(?P<username>[\w]+)/$',
        delete_schedule,
        name='delete-schedule',
    ),
)

hospital/urls.py
from django.conf.urls import patterns, url
import views

urlpatterns = patterns('',

    url(r'^$', views.index, name='system_home'),

)

patient/urls.py
from django.conf.urls import patterns, url
from patient import views

urlpatterns = patterns('',

    url(r'^register$', views.register, name='patient_register'),
    url(r'^home$', views.home, name='patient_home'),
    
)

physician/urls.py
from django.conf.urls import patterns, url
from physician import views

urlpatterns = patterns('',

    url(r'^register$', views.register, name='doc_register'),
    url(r'^home$', views.home, name='doc_home'),
    url(r'^doc_search$', views.doc_search, name='doc_search'),
    url(r'^download$',views.download,name='download'),

)

Receptionist/models.py
from django.db import models
from django.contrib.auth.models import User

from hospital.models import Staff
class Receptionist(Staff):
     def __init__(self, *args, **kwargs):
        super(Receptionist,self).__init__(*args, **kwargs)
        self.__model_label__ = 'Receptionist'
        self._parent_model = 'Staff'
     #user=models.OneToOneField(User,primary_key=True,verbose_name='rec')
    #define methods here

Receptionist/views.py
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.template import RequestContext
from django.contrib import auth
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from Receptionist.search import *
from patient.models import Patient
from django.contrib.auth.models import User
from urllib import urlencode
from patient.models import Guardian
from models import Receptionist



def search_rec(request):
    try:
        if not (request.user.is_authenticated() and request.user.profile.user_type==0)  :
            d = {'server_message':"Not Logged In."}
            query_str = urlencode(d)
            return HttpResponseRedirect('/login_all/?' +query_str)
    except:
            d = {'server_message':"not logged in"}
            query_str = urlencode(d)
            return HttpResponseRedirect('/login_all/?' +query_str)
    if request.method == 'GET':
        rec=Receptionist.objects.get(user=request.user)
        if request.GET.get("submit_search_button"): # if search submit button clicked
            query_string = ''
            found_entries = None
            if ('q' in request.GET) and request.GET['q'].strip():
                query_string = request.GET['q']

                entry_query = get_query(query_string, ['firstname', 'lastname','patient_section','patient_room','user__username'])

                found_entries = Patient.objects.filter(entry_query)
                found_entries=found_entries.filter(parent_hospital= rec.hospital)

            return render_to_response('Receptionist/rec_search.html',
                          { 'query_string': query_string, 'found_entries': found_entries },
                          context_instance=RequestContext(request))

    #To Do: Handle Other parts of Receptionsit Here

    return render_to_response('Receptionist/rec_search.html',{},context_instance=RequestContext(request))

###########################################################################################################

from django.shortcuts import render_to_response
from rest_framework import viewsets


from patient.models import Patient
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import DeleteView
from django.template import RequestContext
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponseNotAllowed
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext_lazy as _


class PatientViewSet(viewsets.ModelViewSet):

    queryset = Patient.objects.all()
    filter_fields = (
        'user'
        'username',
        'firstname',
        'lastname',
        'gender',
        'patient_section',
        'patient_room',
        'gender',
    )

    def pre_save(self, obj):
        user = self.request.user
        obj.superuser = user
        super(PatientViewSet, self).pre_save(obj)


def patient_list_view(request):
    try:
        if not (request.user.is_authenticated() and request.user.profile.user_type==0)  :
            d = {'server_message':"Not Logged In."}
            query_str = urlencode(d)
            return HttpResponseRedirect('/login_all/?' +query_str)
    except:
            d = {'server_message':"not logged in"}
            query_str = urlencode(d)
            return HttpResponseRedirect('/login_all/?' +query_str)

    patients = None
    search = request.GET.get("search", False)
    rec=Receptionist.objects.get(user=request.user)
    if search:
        try:
            patients = Patient.objects.filter(username__icontains=search) | \
                Patient.objects.filter(firstname__icontains=search) | \
                Patient.objects.filter(lastname__icontains=search)
        except Exception, e:
            patients = None
    else:
        patients = Patient.objects.all()
        patients=patients.filter( parent_hospital= rec.hospital)
    ctx = {'patients': patients}

    return render_to_response(
        'Receptionist/list.html',
        ctx,
        context_instance=RequestContext(request),
    )


# class PatientDetailView( DetailView):
#     model = Patient
#     pk_url_kwarg = 'username'
#     template_name = 'Receptionist/detail.html'
def detail(request,username):
    patient=Patient.objects.get(username=username)
    try:
        ward=Guardian.objects.get(patient_detail=patient)
    except:
        ward=None
    try:
        sch=schedule.objects.get(patient=patient)
    except:
            sch=None
    ctx = {'patient': patient,'ward':ward,'sch':sch}


    return render_to_response(
        'Receptionist/detail.html',
        ctx,
        context_instance=RequestContext(request),
    )


# solo como superuser
# class PatientDeleteView( DeleteView):
#     model = Patient
#     success_url = reverse_lazy('rec_app:patients-list')
#     #pk_url_kwarg = 'username'
#     template_name = 'Receptionist/delete.html'

def delete(request,username):
    patient=Patient.objects.get(username=username)
    ctx = {'patient': patient}
    if request.method=="POST":
        patient.delete()
        return HttpResponseRedirect(reverse('rec_app:patients-list'))
    return render_to_response(
        'Receptionist/delete.html',
        ctx,
        context_instance=RequestContext(request),
    )

def record_patient(request):
      birth=request.POST['birthday']
      fname=request.POST['first_name']
      lname=request.POST['last_name']
      usrname=request.POST['username']
      user=User.objects.create_user(username=usrname ,
                password=request.POST['ssn'],
                first_name=fname,
                last_name=lname,
                email=request.POST['email']
                )
      user.save()

      section=request.POST['section']
      room=request.POST['room']
      rec=Receptionist.objects.get(user=request.user)
      patient=Patient(  username=usrname,
                        parent_hospital=rec.hospital,
                        user_type=2,
                        user=user,
                        firstname=fname,
                        lastname=lname,
                        Tel=request.POST['Tel'],
                        ssn=request.POST['ssn'],
                        birthday=birth,
                        age=request.POST['age'],
                        marital_status=request.POST['marital_status'],
                        occupation=request.POST['occupation'],
                        country=request.POST['country'],
                        city=request.POST['city'],
                        district=request.POST['district'],
                        street=request.POST['street'],
                        alley=request.POST['alley'],
                        building_no=request.POST['building_no'],
                        postal_code=request.POST['postal_code'],
                        gender=request.POST['gender'],
                        patient_room=room,
                        patient_section=section
                    )
      patient.save()

      return patient


def patient_create_view(request):
    #if request.user.is_authenticated() and request.user.is_superuser:
        if request.method == "POST":
            patient = record_patient(request)
            if patient:
                return HttpResponseRedirect(
                    reverse('rec_app:patients-list')
                )

        return render_to_response(
            'Receptionist/create.html',
            context_instance=RequestContext(request),
        )




def update_patient(request, username):

      section=request.POST['section']
      room=request.POST['room']
      birth=request.POST['birthday']
      fname=request.POST['first_name']
      lname=request.POST['last_name']
      email=request.POST['email']
      Tel=request.POST['Tel']
      ssn=request.POST['ssn']
      age=request.POST['age']
      marital_status=request.POST['marital_status']
      occupation=request.POST['occupation']
      country=request.POST['country']
      city=request.POST['city']
      district=request.POST['district']
      street=request.POST['street']
      alley=request.POST['alley']
      building_no=request.POST['building_no']
      postal_code=request.POST['postal_code']
      gender=request.POST['gender']

      #patient = get_object_or_404(Patient, pk=username)
      try:
            patient=Patient.objects.get(username=username)
      except:
            patient=None

      patient.user.first_name=fname
      patient.user.last_name=lname
      patient.user.email=email


      patient.Tel=Tel
      patient.ssn=ssn
      patient.age=age
      patient.marital_status=marital_status
      patient.occupation=occupation
      patient.country=country
      patient.city=city
      patient.district=district
      patient.street=street
      patient.alley=alley
      patient.building_no=building_no
      patient.postal_code=postal_code
      patient.gender=gender
      patient.birthday=birth
      patient.patient_room=room
      patient.patient_section=section
      patient.save()
      return patient


def patient_update_view(request, username):

        if request.method == "POST":
            patient = update_patient(request,username)
            if patient:
                return HttpResponseRedirect(
                    reverse('rec_app:patients-list')
                )

        #patient = get_object_or_404(Patient, pk=username)
        try:
            patient=Patient.objects.get(username=username)
        except:
            patient=None

        ctx = {'patient': patient}

        return render_to_response(
            'Receptionist/update.html',
            ctx,
            context_instance=RequestContext(request),
        )

################################################################## Guardian Allocation

Receptionist/templates/Receptionist/Create_delete_update_Patient_base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
	<title>CHMS | PatientList</title>
	  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <!-- FontAwesome -->
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <!-- Navbar -->

         <link href="{% static 'css/recNew.css' %}" rel="stylesheet">

</head>

<body>

<div class="header">
	<ul>
		<li class="brand"><img src="{% static 'logo.png' %}"></li>
		<a href="{% url 'rec_app:patients-list' %}"><li>Patient List</li></a>
        <a href="{% url 'rec_app:rec_search' %}"><li>Search</li></a>
        <a href="{% url 'rec_app:patients-create' %}"><li>BedRidden Registeration</li></a>
        <a href="{% url 'messages_inbox' %}"><li>Messages</li></a>
        <a href="{% url 'logout' %}"><li>LogOut</li></a>
	</ul>
</div>
{% block content %}






  <script src="{% static 'js/jquery.js' %}"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
{% endblock content %}

<div class="container">
</div> <div class="forground"></div>
<div class="pattern"></div>
</body>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{ % static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>

</html>

Receptionist/templates/Receptionist/delete_schedule.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
	<title>CHMS | PatientList</title>
	  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
      <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
       <link href="{% static 'css/recNew.css' %}" rel="stylesheet">
</head>
<body>

<div class="header">
	<ul>
		<li class="brand"><img src="{% static 'logo.png' %}"></li>
		<a href="{% url 'rec_app:patients-list' %}"><li>Patient List</li></a>
        <a href="{% url 'rec_app:rec_search' %}"><li>Search</li></a>
        <a href="{% url 'rec_app:patients-create' %}"><li>BedRidden Registeration</li></a>
        <a href="{% url 'messages_inbox' %}"><li>Messages</li></a>
        <a href="{% url 'rec_app:patients-detail' patient.username %}" > <li>Back to Patient Detail</li> </a>
	</ul>
</div>
{% block content %}
    <article>
        <p> &nbsp</p>
        <p> &nbsp</p>
        <p> &nbsp</p>
        <p> &nbsp</p>
        <p> &nbsp</p>
    </article>

<div class="panel panel-primary">

  <div class="panel-heading">
    <h1 class="panel-title">
      Schedule <strong>{{ sch.event|title }} </strong> <i class="fa fa-trash"></i>
    </h1>
  </div>

  <article class="panel-body">
    <form action="" method="post">
      {% csrf_token %}

      <p>Are you sure to remove <strong>{{ sch.event|title }} </strong> ?</p>
     <article>
        <p> &nbsp</p>
    </article>
      <p>
        <button type="submit"  class="btn btn-danger btn-block"/>Confirm</button>
      </p>
    </form>

  </article>

  <script src="{% static 'js/jquery.js' %}"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

{% endblock content %}
</div>


<div class="container">
</div><div class="forground"></div>
<div class="pattern"></div>
</body>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{ % static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>

</html>

Receptionist/templates/Receptionist/delete_ward.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
	<title>CHMS | PatientList</title>
	  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
      <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
       <link href="{% static 'css/recNew.css' %}" rel="stylesheet">
</head>
<body>

<div class="header">
	<ul>
		<li class="brand"><img src="{% static 'logo.png' %}"></li>
		<a href="{% url 'rec_app:patients-list' %}"><li>Patient List</li></a>
        <a href="{% url 'rec_app:rec_search' %}"><li>Search</li></a>
        <a href="{% url 'rec_app:patients-create' %}"><li>BedRidden Registeration</li></a>
        <a href="{% url 'messages_inbox' %}"><li>Messages</li></a>
        <a href="{% url 'rec_app:patients-detail' patient.username %}" > <li>Back to Patient Detail</li> </a>
	</ul>
</div>
{% block content %}
    <article>
        <p> &nbsp</p>
        <p> &nbsp</p>
        <p> &nbsp</p>
        <p> &nbsp</p>
        <p> &nbsp</p>
    </article>
<div class="panel panel-primary">

  <div class="panel-heading">
    <h1 class="panel-title">
      Delete Guardian <strong>{{ ward.guardian_name|title }} </strong> <i class="fa fa-trash"></i>
    </h1>
  </div>

  <article class="panel-body">
    <form action="" method="post">
      {% csrf_token %}
      <p>Are you sure to remove <strong>{{ ward.guardian_name|title }} </strong> ?</p>
            <article>
        <p> &nbsp</p>
    </article>
      <p>
        <button type="submit"  class="btn btn-danger btn-block"/>Confirm</button>
      </p>
    </form>

  </article>

  <script src="{% static 'js/jquery.js' %}"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

{% endblock content %}
</div>


<div class="container">
</div><div class="forground"></div>
<div class="pattern"></div>
</body>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{ % static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>

</html>

Receptionist/templates/Receptionist/detail.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
	<title>CHMS | Patient Detail</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/search.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/detail.css' %}">
</head>

<body>



  <div class="header">
      <ul class="header ul li">

        <li class="brand"><img src="{% static 'logo.png' %}"></li>
        <a href="{% url 'rec_app:patients-list' %}"><li>Patient List</li></a>
        <a href="{% url 'rec_app:rec_search' %}"><li>Search</li></a>
        <a href="{% url 'rec_app:patients-create' %}"><li>BedRidden Registeration</li></a>
        <a href="{% url 'messages_inbox' %}"><li>Messages</li></a>
        <a href="{% url 'history_records:system_home' patient.user.username %}"><li>Patient History</li></a>
        {% if not ward %}
         <a href="{% url 'rec_app:allocate-ward' patient.username %}"> <li>Allocate Guardian </li></a>
         {% else %}
         <a href="{% url 'rec_app:update-ward' patient.username %}" > <li>Update Guardian</li> </a>
        {% endif %}
     {% if not sch %}
      <a href="{% url 'rec_app:set-schedule' patient.username %}" > <li>Set Schedule</li> </a>
      {% else %}
      <a href="{% url 'rec_app:update-schedule' patient.username %}" ><li> Update Schedule</li> </a>
      {% endif %}
          <a href="{% url 'logout' %}"><li>LogOut</li></a>
      </ul>
  </div>



<div class="container">
 {% block content %}

<div >

  <div >
    <h1>
      Patient Specifications
    </h1>
      <p>This is {{ patient.firstname }} {{ patient.lastname}} details</p>
       <ul>
      <li><div class="btn success"><a href="{% url 'rec_app:patients-list' %}"  >  Back To List  </a></div></li>
      <li>    </li>
      <li><div class="btn success"><a href="{% url 'rec_app:patients-update' patient.username %}"  >Modify This</a></div></li>
       <li>    </li>
      <li><div class="btn warning"><a href="{% url 'rec_app:patients-delete' patient.username %}" > Delete This </a></div></li>
    </ul>
  </div>

  <div class="sheet">


        <table>
		<tr class="blue">
			<td  >Username </td>
			<td> {% if patient.username %} {{ patient.username }} {% endif %} </td>
		</tr>
		<tr class="blue">
			<td>Firstname </td>
			<td> {% if patient.user.first_name %} {{ patient.user.first_name|title }}{% endif %} </td>
		</tr>
		<tr class="blue">
			<td>Lastname </td>
			<td> {% if patient.user.last_name %}{{ patient.user.last_name|title }}{% endif %} </td>
		</tr>
		<tr class="blue">
			<td>Section </td>
			<td> {% if patient.patient_section %} {{ patient.patient_section }}{% endif %} </td>
		</tr>
		<tr class="blue">
			<td>Room </td>
			<td> {% if patient.patient_room %}{{ patient.patient_room}}{% endif %} </td>
		</tr>
		<tr class="blue">
			<td>SSN </td>
			<td> {% if patient.ssn %}{{ patient.ssn }}{% endif %} </td>
		</tr>
		<tr class="blue">
			<td>Age </td>
			<td> {% if patient.age %} {{ patient.age }}<{% endif %} </td>
		</tr>
		<tr class="blue">
			<td>Birthday </td>
			<td> {% if patient.birthday %}{{ patient.birthday}}<{% endif %} </td>
		</tr>
		<tr class="blue">
			<td>Gender </td>
			<td> {% if patient.gender %} {{ patient.gender }}{% endif %} </td>
		</tr>


		<tr class="blue">
			<td>Address </td>
			<td>  {% if patient.get_address_as_string %} {{ patient.get_address_as_string }}{% endif %} </td>
		</tr>
		<tr class="blue">
			<td>Email </td>
			<td> {% if patient.email %} {{ patient.email }}{% endif %} </td>
		</tr>
		<tr class="blue">
			<td>Tel </td>
			<td> {% if patient.Tel %}{{ patient.Tel }}{% endif %} </td>
		</tr>
		<tr class="blue">
			<td>marital_status </td>
			<td> {% if patient.marital_status %}{{ patient.marital_status }}{% endif %} </td>
		</tr>

		<tr class="blue">
			<td>occupation </td>
			<td> {% if patient.occupation %}{{ patient.occupation }}{% endif %} </td>
		</tr>


		<tr class="red">
			<td>Guardian Name </td>
			<td> {% if ward %} {{ ward.guardian_name }}{% endif %} </td>
		</tr>

		<tr class="red">
			<td>Guardian Relation </td>
			<td> {% if ward %}{{ ward.relation_to_guardian }}{% endif %} </td>
		</tr>
		<tr class="red">
			<td>Guardian Phone </td>
			<td> {% if ward %}{{ ward.guardian_phone }}{% endif %} </td>
		</tr>


		<tr class="green">
			<td>Event </td>
			<td> {% if sch %} {{ sch.event }}{% endif %} </td>
		</tr>
		<tr class="green">
			<td>Event Date </td>
			<td> {% if sch %} {{ sch.event_date }}{% endif %} </td>
		</tr>
		<tr class="green">
			<td>Event Time </td>
			<td> {% if sch %} {{ sch.event_time }}{% endif %} </td>
		</tr>
		<tr class="green">
			<td>Related_division </td>
			<td> {% if sch %} {{ sch.related_division }}{% endif %} </td>
		</tr>
		<tr class="green">
			<td>Description </td>
			<td>{% if sch %} {{ sch.description }} {% endif %} </td>
		</tr>

            <div class="forground"></div>
	</table>
    <article>
        <p> &nbsp</p>
        <p> &nbsp</p>
        <p> &nbsp</p><p> &nbsp</p>


    </article>


  </div>

</div>
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{ % static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script type="text/javascript">
	$('input.btn').hoverIntent(function(){
		$(this).animate({"border-radius": "-=30px"},300);
	},function(){$(this).animate({"border-radius": "+=30px"},300);});
</script>
{% endblock content %}
</body>

</html>

     

Receptionist/templates/Receptionist/rec_search.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>CHMS | SEARCH</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/general-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/search.css' %}">
</head>
<body>
<div class="header">
	<ul>
		<li class="brand"><img src="{% static 'logo.png' %}"></li>
		<a href="{% url 'rec_app:patients-list' %}"><li>Patient List</li></a>
        <a href="{% url 'doc_app:doc_register' %}"><li>Physician Register</li></a>
		<a href="{% url 'patient_app:patient_register' %}"><li>Patient Register</li></a>
        <a href="{% url 'messages_inbox' %}"><li>Messages</li></a>
		<a href="{% url 'logout' %}"><li>LogOut</li></a>
	</ul>
</div>
<div class="search">
		<h1 style="color:#34495e">Search Patient</h1>
		<p>Receptionist Search Panel</p>
	<form method="get" action="">
		<input class="large"  type="text" name="q" id="id_q" placeholder="search" />
        <input class="btn  warning" type="submit" value="Submit" name="submit_search_button" />

	</form>
</div>
<div class="result">
	<table>
<thead>
      <tr>
        <th>Username</th>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Section</th>
        <th>Room</th>
        <th>Age</th>
        <th>Gender</th>

      </tr>
    </thead>
    <tbody>
      {% for patient in found_entries %}
        <tr>
          <td><a style="color:#34495e" href="{% url 'rec_app:patients-detail' patient.username %}">{{ patient.username }}</a></td>
          <td>{{ patient.user.first_name }}</td>
          <td>{{ patient.user.last_name }}</td>
            <td>{{ patient.patient_section }}</td>
            <td>{{ patient.patient_room }}</td>
          <td>{{ patient.age }}</td>
          <td>
            {% if patient.gender == 'M' %}
              <i class="fa fa-male"></i> M
            {% else %}
              <i class="fa fa-female"></i> F
            {% endif %}
          </td>



        </tr>
      {% endfor %}
    </tbody>
	</table>
</div>
<div class="pattern"></div>
</body>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{ % static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script type="text/javascript">
	$('input.btn').hoverIntent(function(){
		$(this).animate({"border-radius": "-=30px"},300);
	},function(){$(this).animate({"border-radius": "+=30px"},300);});
</script>
</html>