CHMS/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()
from CHMS import views

from django.conf import settings

# ... your normal urlpatterns here




urlpatterns = patterns('',

    url(r'hospital/$', include('hospital.urls')),
    url(r'pharmacy/', include('pharmacy.urls',namespace='phar_app')),
    url(r'history/', include('history_records.urls',namespace='history_records')),
    url(r'app/', include('androidApp.urls',namespace='android_app')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^patient/',include('patient.urls',namespace='patient_app')),
    url(r'^$', views.firstpage , name = 'firstpage'),
    url(r'^SystemHomePage/',views.SystemHomePage,name='SystemHomePage'),
    url(r'^PatientSearch/',views.PatientSearch,name='PatientSearch'),
    url(r'^rec/',include('Receptionist.urls', namespace='rec_app')),
    url(r'^login_all/',views.login,name='login_all'),
    url(r'^logout/',views.logout,name='logout'),
    url(r'^medicine/', include('medicine.urls',namespace='medicine_app')), # pharmacy
    url(r'^reports/',views.get_reports,name='reports'),
    url(r'^physician/',include('physician.urls',namespace='doc_app')),
    url(r'^messages/', include('django_messages.urls')),
    
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

hospital/urls.py
from django.conf.urls import patterns, url
import views

urlpatterns = patterns('',

    url(r'^$', views.index, name='system_home'),

)

physician/urls.py
from django.conf.urls import patterns, url
from physician import views

urlpatterns = patterns('',

    url(r'^register$', views.register, name='doc_register'),
    url(r'^home$', views.home, name='doc_home'),
    url(r'^doc_search$', views.doc_search, name='doc_search'),
    url(r'^download$',views.download,name='download'),

)

physician/models.py
from django.db import models
from hospital.models import Staff,Hospital

class Physician(Staff):

    DEGREE_CHOICES = (
        ('DE','dentist'),
        ('GP', 'general practitioner'),
        ('SP', 'Specialist'),
        ('SSP','SSP')
        
    )
    SPECIALITY_CHOICES = (
            ('cr','cardialogist'), 
            ('dr','dermatologist'), 
            ('en','endocrinologist'), 
            ('ent','ENT (Ear Nose Throat) Specialist'), 
            ('ge','Gerontologist'), 
            ('gy','Gynaecologist'), 
            ('ha','Haematologist'), 
            ('in','Internist'), 
            ('ne','Neurologist'),  
            ('ob','Obstetrician'), 
            ('on','Oncologist'), 
            ('op','Ophthalmologist'), 
            ('or','Orthodontist'), 
            ('ort','Orthopaedis'), 
            ('pd','Pediatrician'), 
            ('po','Podiatrist'), 
            ('ra','Radiologist'), 
            ('sr','Surgeon'), 
            ('ur','Urologist'),        
                          )

    specialty=models.CharField(max_length=3,choices=SPECIALITY_CHOICES)
    graduation_university_name=models.CharField(max_length=200,null=True,blank=True)
    graduation_university_country=models.CharField(max_length=200,null=True,blank=True)
    graduation_university_city=models.CharField(max_length=200,null=True,blank=True)
    degree=models.CharField(max_length=2,choices=DEGREE_CHOICES)
    

    def __unicode__(self):
        return self.user.username

    

physician/views.py
from models import *
from django.contrib.auth.models import User
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.template import RequestContext
from django.core.context_processors import csrf
from urllib import urlencode
from patient.models import *
from django.core.urlresolvers import reverse
from Receptionist.search import *
from django.conf import settings
from django.core.servers.basehttp import FileWrapper
from django.utils.encoding import smart_str
import os
import mimetypes
from models import Physician
from Receptionist.models import Receptionist

def register(request):
   try:
        if not (request.user.is_authenticated() and request.user.profile.user_type==0)  :
            return HttpResponse("server_message: Access Denied")
   except:
            return HttpResponse("server_message: Access Denied")
   c={}
   if request.method=="POST":
       try:
            birth=request.POST['birthday']
            fname=request.POST['first_name']
            lname=request.POST['last_name']
            user=User.objects.create_user(username=request.POST['username'] ,
                password=request.POST['ssn'],
                first_name=fname,
                last_name=lname,
                email=request.POST['email']
                )
            user.save()
            rec=Receptionist.objects.get(user=request.user)
            physician=Physician(
                        hospital=rec.hospital,
                        user_type=6,
                        user=user,
                        Tel=request.POST['tel'],
                        ssn=request.POST['ssn'],
                        birthday=birth,
                        age=request.POST['age'],
                        marital_status=request.POST['marital_status'],
                        is_staff_head=request.POST['is_staff_head'],
                        country=request.POST['country'],
                        city=request.POST['city'],
                        district=request.POST['district'],
                        street=request.POST['street'],
                        alley=request.POST['alley'],
                        building_no=request.POST['building_no'],
                        postal_code=request.POST['postal_code'],
                        specialty=request.POST.get('speciality','ent'),
                        graduation_university_name=request.POST['graduation_university_name'],
                        graduation_university_country=request.POST['graduation_university_country'],
                        graduation_university_city=request.POST['graduation_university_city'],
                        degree=request.POST['degree'])
            physician.save()
       except:
            try:
                if user:
                    user.delete()
                if physician:
                    physician.delete()
            except:
                pass
            return HttpResponse("An Error Has Occured During Registration, Since Required Fields Are Not    \
                                Entered Properly , Please Try Again" )


       c.update(csrf(request))
       return HttpResponseRedirect(reverse('rec_app:rec_search'))
   return render_to_response('physician/register.html',c,context_instance=RequestContext(request))



def home(request):
   try:
       if not (request.user.is_authenticated() and request.user.profile.user_type==6):
           d = {'server_message':"Not Logged In."}
           query_str = urlencode(d)
           return HttpResponseRedirect('/login_all/?' +query_str)
   except:
           d = {'server_message':"not logged in"}
           query_str = urlencode(d)
           return HttpResponseRedirect('/login_all/?' +query_str)

   try:
       doc=Physician.objects.get(user=request.user)
   except:
       doc=None

   c={'doc':doc}
   c.update(csrf(request))
   return render_to_response('physician/physician_home.html',c,context_instance=RequestContext(request))


def doc_search(request):
    try:
        if not (request.user.is_authenticated() and request.user.profile.user_type==6)  :
            d = {'server_message':"Not Logged In."}
            query_str = urlencode(d)
            return HttpResponseRedirect('/login_all/?' +query_str)
    except:
            d = {'server_message':"not logged in"}
            query_str = urlencode(d)
            return HttpResponseRedirect('/login_all/?' +query_str)
    if request.method == 'GET':
        doc=Physician.objects.get(user=request.user)
        if request.GET.get("submit_search_button"):
            query_string = ''
            found_entries = None
            if ('q' in request.GET) and request.GET['q'].strip():
                query_string = request.GET['q']

                entry_query = get_query(query_string, ['firstname', 'lastname','patient_section','patient_room','user__username'])

                found_entries = Patient.objects.filter(entry_query)
                found_entries=found_entries.filter(parent_hospital= doc.hospital)

            return render_to_response('physician/doc_search.html',
                          { 'query_string': query_string, 'found_entries': found_entries },
                          context_instance=RequestContext(request))


    return render_to_response('physician/doc_search.html',{},context_instance=RequestContext(request))

def download(request,file_name="app.txt"):
    file_path = settings.MEDIA_ROOT +'/'+ file_name
    file_wrapper = FileWrapper(file(file_path,'rb'))
    file_mimetype = mimetypes.guess_type(file_path)
    response = HttpResponse(file_wrapper, content_type=file_mimetype )
    response['X-Sendfile'] = file_path
    response['Content-Length'] = os.stat(file_path).st_size
    response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(file_name)
    return response

physician/templates/physician/doc_search.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>Physician| Search</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/general-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/search.css' %}">
</head>
<body>
<div class="header">
	<ul>
		<li class="brand"><img src="{% static 'logo.png' %}"></li>
        <a href="{% url 'doc_app:doc_home' %}"><li>Profile</li></a>
        <a href="{% url 'messages_inbox' %}"><li>Messages</li></a>
	</ul>
</div>
<div class="search">
		<h1 style="color:#34495e">Search Patient</h1>
		<p>Physician Search Panel</p>
	<form method="get" action="">
		<input class="large"  type="text" name="q" id="id_q" placeholder="search" />
        <input class="btn  warning" type="submit" value="Submit" name="submit_search_button" />

	</form>
</div>
<div class="result">
	<table>
<thead>
      <tr>
        <th>Username</th>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Section</th>
        <th>Room</th>
        <th>Age</th>
        <th>Gender</th>

      </tr>
    </thead>
    <tbody>
      {% for patient in found_entries %}
        <tr>
          <td><a href="{% url 'history_records:system_home' patient.user.username %}">{{ patient.user.username }}</a></td>
          <td>{{ patient.user.first_name }}</td>
          <td>{{ patient.user.last_name }}</td>
            <td>{{ patient.patient_section }}</td>
            <td>{{ patient.patient_room }}</td>
          <td>{{ patient.age }}</td>
          <td>
            {% if patient.gender == 'M' %}
              <i class="fa fa-male"></i> M
            {% else %}
              <i class="fa fa-female"></i> F
            {% endif %}
          </td>



        </tr>
      {% endfor %}
    </tbody>
	</table>
</div>
<div class="pattern"></div>
</body>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{ % static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script type="text/javascript">
	$('input.btn').hoverIntent(function(){
		$(this).animate({"border-radius": "-=30px"},300);
	},function(){$(this).animate({"border-radius": "+=30px"},300);});
</script>
</html>

physician/templates/physician/physician_home.html
<!DOCTYPE html>
{% load staticfiles %}
{%load static%}
<html>
<head>
	<title>Doctor|Home</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/general-style.css' %}">
	    <link rel="stylesheet" type="text/css" href="{% static 'css/patient_home.css' %}">
</head>
<body>
<div class="sidebar">
	<ul>
		<a class="btn warning" href="#profile"><li class="btn"li>Profile</li></a>
		<a class="btn warning" href="{% url 'doc_app:download' %}"><li  class="btn warning "> DownloadApp</li></a>
		<a class="btn warning" href="{% url 'messages_inbox' %}"><li  class="btn warning ">Messages</li></a>
		<a class="btn warning" href="{% url 'doc_app:doc_search' %}"><li class="btn warning ">Search</li></a>
        <a class="btn warning" href="{% url 'logout' %}"><li class="btn warning ">Log Out</li></a>
	</ul>
</div>
<div class="main">
	<div class="module" id="profile">
        {% if doc.photo %}
		<p><img src={{doc.photo.url}}></p>
        {% else %}
        <img src="{% static 'congruent_pentagon.png' %}">
        {% endif %}
		<p>Username : {{ doc.user.username}} </p>
		<p>FirstName : {{ doc.user.first_name}} </p>
		<p>LastName : {{ doc.user.last_name}} </p>
		<p>Email: {{ doc.user.email}}</p>
		<p>social security number :{{ doc.ssn}} </p>
		<p>Birthday : {{ doc.birthday }}</p>
		<p>Age : {{ doc.age }}</p>
		<p>Address : {{ doc.get_address_as_string }}</p>
            <p>&nbsp</p>
        <p>&nbsp</p>
        <p>&nbsp</p>
        <p>&nbsp</p>
	</div>

</div>
<div class="pattern"></div>
</body>
<script src="js/jquery.js"></script>
<script src="js/hoverIntent.js"></script>
<script src="js/script.js"></script>
<script type="text/javascript">
	$('li.btn').hoverIntent(function(){
		round($(this));
	},function(){});
</script>
</html>

physician/templates/physician/register.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
	<title>Register</title>
	<link rel="stylesheet" type="text/css" href='{% static "style.css" %} '>
</head>
<body>
	<form method="post" >
	{% csrf_token %}
		<legend>Physician Registration Form</legend>
		<hr>
		<p><input name="username" placeholder="Username">  </p>
		<p><input name="first_name" placeholder="Firstname">  </p>
		<p><input name="last_name" placeholder="Lastname">  </p>
		<p><input name="email" type="email" placeholder="Email">  </p>
		<p><input name="tel" type="tel" placeholder="Tel">  </p>
		<p><input name="ssn" placeholder="ssn"></p>
		<p><input name="birthday" type="date" placeholder="Birthday"></p>
		<p><input name="age" placeholder="Age"></p>
		<p> 
			<select name="marital_status">
				<option value="0">single</option>
				<option value="1">married</option>
			</select>
		</p>
        <p>
			<select name="is_staff_head">
				<option value="True">Is Head</option>
				<option value="False">Is Not Head</option>
			</select>
		</p>
		<p><input name="country" placeholder="Country">  </p>
		<p><input name="city" placeholder="City">  </p>
		<p><input name="district" placeholder="District">  </p>
		<p><input name="street" placeholder="Street">  </p>
		<p><input name="alley" placeholder="Alley">  </p>
		<p><input name="building_no" placeholder="Building-no">  </p>
		<p><input name="postal_code" placeholder="Postal Code">  </p>
        <p>
			<select name="speciality">
				<option value="cr">cardialogist</option>
				<option value="dr">dermatologist</option>
                <option value="en">endocrinologist</option>
                <option value="ent">Ear Nose Throat</option>
                 <option value="ge">Gerontologist</option>
                <option value="gy">Gynaecologist</option>
                <option value="ha">Haematologist</option>
                <option value="in">Internist</option>
                <option value="ne">Neurologist</option>
                <option value="ob">Obstetrician</option>
                <option value="on">Oncologist</option>
                <option value="op">Ophthalmologist</option>
                <option value="or">Orthodontist</option>
                <option value="ort">Orthopaedis</option>
                <option value="pd">Pediatrician</option>
                <option value="po">Podiatrist</option>
                <option value="ra">Radiologist</option>
                <option value="sr">Surgeon</option>
                <option value="ur">Urologist</option>
			</select>
		</p>
		<p><input name="graduation_university_name" placeholder="graduation university name"></p>
		<p><input name="graduation_university_country" placeholder="graduation university country"></p>
		<p><input name="graduation_university_city" placeholder="graduation university city"></p>
        <p>
			<select name="degree">
				<option value="DE">dentist</option>
				<option value="GP">general practitioner</option>
                <option value="SP">Specialist</option>
                <option value="SSP">SSP</option>
			</select>
		</p>
		<br>
		<input type="submit">
	</form>
</body>
</html>