CHMS/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()
from CHMS import views

from django.conf import settings

# ... your normal urlpatterns here




urlpatterns = patterns('',

    url(r'hospital/$', include('hospital.urls')),
    url(r'pharmacy/', include('pharmacy.urls',namespace='phar_app')),
    url(r'history/', include('history_records.urls',namespace='history_records')),
    url(r'app/', include('androidApp.urls',namespace='android_app')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^patient/',include('patient.urls',namespace='patient_app')),
    url(r'^$', views.firstpage , name = 'firstpage'),
    url(r'^SystemHomePage/',views.SystemHomePage,name='SystemHomePage'),
    url(r'^PatientSearch/',views.PatientSearch,name='PatientSearch'),
    url(r'^rec/',include('Receptionist.urls', namespace='rec_app')),
    url(r'^login_all/',views.login,name='login_all'),
    url(r'^logout/',views.logout,name='logout'),
    url(r'^medicine/', include('medicine.urls',namespace='medicine_app')), # pharmacy
    url(r'^reports/',views.get_reports,name='reports'),
    url(r'^physician/',include('physician.urls',namespace='doc_app')),
    url(r'^messages/', include('django_messages.urls')),
    
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

history_records/urls.py
from django.conf.urls import patterns, url
import views

urlpatterns = patterns('',

    url(r'^(?P<username>[\w]+)/$', views.index, name='system_home'),
    # url(r'^show$',views.show,name='show_history')
    url(r'^(?P<username>[\w]+)/(?P<file_id>\d+)/$', views.medical_file, name='medical_file'),
    url(r'^(?P<username>[\w]+)/(?P<file_id>[\d]+)/medical_history$', views.medical_history, name='medical_history'),
    url(r'^(?P<username>[\w]+)/(?P<file_id>[\d]+)/progress_notes$', views.progress_notes, name='progress_notes'),
    url(r'^(?P<username>[\w]+)/(?P<file_id>[\d]+)/physician_orders$', views.physician_orders, name='phycisian_orders'),
    url(r'^(?P<username>[\w]+)/(?P<file_id>[\d]+)/unit_summary$', views.unit_summary, name='unit_summary'),
    url(r'^(?P<username>[\w]+)/create_file$', views.create_medical_file, name='create_medical_file'),
    url(r'^(?P<username>[\w]+)/create_file_index$', views.create_file, name='create_medical_file_index'),

)

pharmacy/urls.py
__author__ = 'soheil'
from django.conf.urls import patterns, url
from pharmacy.views import login

urlpatterns = patterns('',

    url(r'^login/$', login, name='login'),

)

hospital/models.py
from django.db import models
from django.contrib.auth.models import User
from equipment.models import physiotherapy ,radiotherapy ,ccu,icu,emergency, women_obstetric,\
                                    internal_div,  Orthopedic_surgery_div,child_div,\
                                    Urology_surgery_div, Eye_surgery_div, General_surgery_div, Heart_surgery_div,\
                                     Face_Plastic_surgery_div, Brain_and_Nerve_surgery_div, ENT_surgery_div

USER_CHOICES = (
       (0,'Receptionist'),
       (1,'Boss'),
       (2,'patient'),
       (3,'systemAdmin'),
       (4,'CasualUser'),
       (5,'Pharmacy'),
       (6,'Physician'),
       (7,'Nurse'),

       #TO DO : more/less user choices
   )
Hospital_STAFF_ROLE = (
    ("non_hospital_staff", "Non Hospital Staff"),
    ('secretary', 'Secretary'),
    ('hospital_admin', "Hospital Administrator"),
    ('hospital_staff', "Hospital Staff"),
    ('nurse', "Nurse"),
    ('physio', "Physiotherapist"),
    ("doctor", "Doctor"),
    #TO DO : more/less  choices
)
Hospital_Type_CHOICES=(
       (0,"public"),
       (1,"private")
   )
class BaseUser(models.Model): #Person
    user_type=models.IntegerField(choices=USER_CHOICES,null=True)
    user=models.OneToOneField(User,primary_key=True,related_name='profile')

    Marital_Status_Choices = (('single', "Single"),
                          ("married", "Married"),
                          )
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )


    #More basic Info
    Tel  = models.CharField(max_length=25,null=True,blank=True)
    ssn = models.CharField(max_length=9, unique=True,null=True)
    birthday = models.DateField(null=True,blank=True)
    age = models.CharField(max_length=10, blank=True, null=True)

    #Extra Info
    marital_status = models.CharField(max_length=250,
                                      choices=Marital_Status_Choices,
                                      default="Single",
                                      blank=True,
                                      null=True)

    marital_status_notes = models.CharField(max_length=250,
                                            null=True,
                                            blank=True)

    occupation = models.CharField(max_length=100,blank=True,null=True)
    occupation_notes = models.CharField(max_length=100,
                                        null=True,
                                        blank=True
                                        )

    #Home address
    country = models.CharField(max_length=200, default = 'Iran')
    city=models.CharField(max_length=25,null=True,blank=True)
    district=models.CharField(max_length=25,null=True,blank=True)
    street=models.CharField(max_length=30,null=True,blank=True)
    alley=models.CharField(max_length=30,null=True,blank=True)
    building_no = models.CharField(max_length=200,null=True,blank=True)
    postal_code=models.CharField(max_length=30,null=True,blank=True)


    gender = models.CharField(max_length=1, choices=GENDER_CHOICES,null=True,blank=True)
    father_name=models.CharField(max_length='20')

    def get_address_as_string(self):
        return '%s - %s, %s\n %s,%s, %s -%s' %(self.country,
                                            self.city,
                                            self.district,
                                            self.street,
                                            self.alley,
                                            self.building_no,
                                            self.postal_code
                                            )


    def __unicode__(self):
          return "%s's profile" % self.user

# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#        profile, created = BaseUser.objects.get_or_create(user=instance)
#     post_save.connect(create_user_profile, sender=User)
class Hospital(models.Model,object): 

   def __init__(self, *args, **kwargs):
      super(Hospital,self).__init__(*args, **kwargs)
      self.__model_label__ = 'hospital'
      self._parent_model = 'hospital'
      self.equipment_labels=list()

   Hospital_ID=models.IntegerField(primary_key=True)
   Hospital_Name=models.CharField(max_length=250)
   Hospital_Type=models.IntegerField(max_length=1,choices=Hospital_Type_CHOICES)

   #hospital equipments attributes & methods
   #units are accessed by their related_name using select_related() method
   physiotherapy=models.OneToOneField(physiotherapy,related_name='physiotherapy',null=True,blank=True)
   radiotherapy=models.OneToOneField(radiotherapy,related_name='radiotherapy',null=True,blank=True)
   ccu=models.OneToOneField(ccu,related_name='ccu',null=True,blank=True)
   icu=models.OneToOneField(icu,related_name='icu',null=True,blank=True)
   internal_div=models.OneToOneField(internal_div,related_name='internal_div',null=True,blank=True)
   child_div=models.OneToOneField(child_div,related_name='child_div',null=True,blank=True)
   emergency=models.OneToOneField(emergency,related_name='emergency',null=True,blank=True)
   women_obstetric=models.OneToOneField(women_obstetric,related_name='women_obstetric',null=True,blank=True)
   Orthopedic_surgery_div=models.OneToOneField(Orthopedic_surgery_div,
                                               related_name='Orthopedic_surgery_div',null=True,blank=True)
   Urology_surgery_div=models.OneToOneField(Urology_surgery_div,related_name='Urology_surgery_div',null=True,blank=True)
   Eye_surgery_div=models.OneToOneField(Eye_surgery_div,related_name='Eye_surgery_div',null=True,blank=True)
   General_surgery_div=models.OneToOneField(General_surgery_div,related_name='General_surgery_div',null=True,blank=True)
   Heart_surgery_div=models.OneToOneField(Heart_surgery_div,related_name='Heart_surgery_div',null=True,blank=True)
   Face_Plastic_surgery_div=models.OneToOneField(Face_Plastic_surgery_div
                                                ,related_name='Face_Plastic_surgery_div',null=True,blank=True)
   Brain_and_Nerve_surgery_div=models.OneToOneField(Brain_and_Nerve_surgery_div,
                                                    related_name='Brain_and_Nerve_surgery_div',null=True,blank=True)
   ENT_surgery_div=models.OneToOneField(ENT_surgery_div,related_name='ENT_surgery_div',null=True,blank=True)
   

   def get_phone_numbers(self):
        try:
            phones=Phone.objects.filter(hospital=self)
        except:
            phones="No Num"
        p=""
        for phone in phones:
            p+="%s | "%str(phone)

        return  p[0:-2]
   @property
   def physiotherapy_object(self):
       try:
           return self.physiotherapy
       except:
           return None
   @property
   def radiotherapy_object(self):
       try:
           return self.radiotherapy
       except:
           return None
   @property
   def ccu_object(self):
       try:
           return self.ccu
       except:
           return None
   @property
   def icu_object(self):
       try:
           return self.icu
       except:
           return None
   @property
   def internal_div_object(self):
       try:
           return self.internal_div
       except:
           return None
   @property
   def child_div_object(self):
       try:
           return self.child_div
       except:
           return None

   @property
   def emergency_object(self):
       try:
           return self.emergency
       except:
           return None
   @property
   def women_obstetric_object(self):
       try:
           return self.women_obstetric
       except:
           return None
   @property
   def Orthopedic_surgery_div_object(self):
       try:
           return self.Orthopedic_surgery_div
       except:
           return None
   @property
   def Urology_surgery_div_object(self):
       try:
           return self.Urology_surgery_div
       except:
           return None
   @property
   def Eye_surgery_div_object(self):
        try:
           return self.Eye_surgery_div
        except:
           return None
   @property
   def General_surgery_div_object(self):
         try:
           return self.General_surgery_div
         except:
           return None
   @property
   def Heart_surgery_div_object(self):
        try:
           return self.Heart_surgery_div
        except:
           return None
   @property
   def Face_Plastic_surgery_div_object(self):
        try:
           return self.Face_Plastic_surgery_div
        except:
           return None
   @property
   def Brain_and_Nerve_surgery_div_object(self):
        try:
           return self.Brain_and_Nerve_surgery_div
        except:
           return None
   @property
   def ENT_surgery_div_object(self):
         try:
           return self.ENT_surgery_div
         except:
           return None

   @property
   def update_equipment_labels(self):
        """ This updates the self.equipments_labels  """
        if self.physiotherapy_object:
            self.equipment_labels+=['physiotherapy']
        if self.radiotherapy_object:
            self.equipment_labels+=["radiotherapy"]
        if self.ccu_object:
            self.equipment_labels+=["ccu"]
        if self.icu_object:
            self.equipment_labels+=["icu"]
        if self.internal_div_object:
            self.equipment_labels+=["internal_div"]
        if self.child_div_object:
            self.equipment_labels+=["child_div"]
        if self.emergency_object:
            self.equipment_labels+=["emergency"]
        if self.women_obstetric_object:
            self.equipment_labels+=["women_obstetric"]

        if self.Orthopedic_surgery_div_object:
            self.equipment_labels+=["Orthopedic_surgery_div"]
        if self.Urology_surgery_div_object:
            self.equipment_labels+=["Urology_surgery_div"]
        if self.Eye_surgery_div_object:
            self.equipment_labels+=["Eye_surgery_div"]
        if self.General_surgery_div_object:

history_records/templates/medical_history/create_file.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>CHMS | Medical File</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/general-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/medical.css' %}">
</head>
<body>
<div class="header">
	<ul>
		<li class="brand"><img src="{% static 'logo.png' %}"></li>
		<a href="{% url 'SystemHomePage' %}"><li>SystemHomePage</li></a>
		<a href="{% url 'phar_app:login' %}"><li>Pharmacy</li></a>
		<a href="{% url 'messages_inbox' %}"><li>Messages</li></a>
		<a href="{% url 'PatientSearch' %}" ><li>Search Patient</li></a>
		<a href="#"><li>Contact</li></a>
		
	</ul>
</div>
<br><br>
<div class="btn warning large"><a class="btn warning" href="{% url 'history_records:create_medical_file'  username  %}">Create New Medical File</a></div>


<div class="pattern"></div>
</body>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script type="text/javascript">
	$('div.btn').hoverIntent(function(){
		$(this).animate({"border-radius": "+=30px"},300);
	},function(){$(this).animate({"border-radius": "-=30px"},300);});
</script>
</html>

history_records/templates/medical_history/medical_file.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>CHMS | Medical File</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/general-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/medical.css' %}">
</head>
<body>
<div class="header">
	<ul>
		<li class="brand"><img src="{% static 'logo.png' %}"></li>
		<a href="{% url 'SystemHomePage' %}"><li>SystemHomePage</li></a>
		<a href="{% url 'phar_app:login' %}"><li>Pharmacy</li></a>
		<a href="{% url 'messages_inbox' %}"><li>Messages</li></a>
		<a href="{% url 'PatientSearch' %}" ><li>Search Patient</li></a>
		<a href="#"><li>Contact</li></a>
		<a href="{% url 'logout' %}"><li>Logout</li></a>
	</ul>
</div>
<br><br>
<div class="btn warning large"><a class="btn warning" href="{% url 'history_records:medical_history'  patient.user.username file.id %}">Medical History Sheet</a></div>

<div class="btn warning large"><a class="btn warning" href="{% url 'history_records:phycisian_orders'  patient.user.username file.id %}">Physician's Order Sheet</a></div>

<div class="btn warning large"><a class="btn warning" href="{% url 'history_records:progress_notes'  patient.user.username  file.id %}">Progress Notes Sheet</a></div>

<div class="btn warning large"><a class="btn warning" href="{% url 'history_records:unit_summary'  patient.user.username  file.id %}">Unit Summary Sheet</a></div>

<div class="pattern"></div>
</body>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script type="text/javascript">
	$('div.btn').hoverIntent(function(){
		$(this).animate({"border-radius": "+=30px"},300);
	},function(){$(this).animate({"border-radius": "-=30px"},300);});
</script>
</html>

history_records/templates/medical_history/medical_files.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>CHMS | Medical File</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/general-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/medical.css' %}">
</head>
<body>
<div class="header">
	<ul>
		<li class="brand"><img src="{% static 'logo.png' %}"></li>
		<a href="{% url 'SystemHomePage' %}"><li>SystemHomePage</li></a>
		<a href="{% url 'phar_app:login' %}"><li>Pharmacy</li></a>
		<a href="{% url 'messages_inbox' %}"><li>Messages</li></a>
		<a href="{% url 'PatientSearch' %}" ><li>Search Patient</li></a>
		<a href="#"><li>Contact</li></a>
        <a href="{% url 'logout' %}"><li>Logout</li></a>
		
	</ul>
</div>
<br><br>
{% for file in files %}
<div class="btn warning large"><a class="btn warning" href="{% url 'history_records:medical_file'  patient.user.username  file.id %}">{{file.date_of_addmition}}</a></div>
{% endfor %}
<div class="btn warning large"><a class="btn warning" href="{% url 'history_records:create_medical_file'  patient.user.username  %}">Create New Medical File</a></div>

<div class="pattern"></div>
</body>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script type="text/javascript">
	$('div.btn').hoverIntent(function(){
		$(this).animate({"border-radius": "+=30px"},300);
	},function(){$(this).animate({"border-radius": "-=30px"},300);});
</script>
</html>

history_records/templates/medical_history/medical_history_form.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>CHMS | Medical File</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/general-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/medical.css' %}">
</head>
<body>
<div class="header">
	<ul>
		<li class="brand"><img src="{% static 'logo.png' %}"></li>
		<a href="{% url 'SystemHomePage' %}"><li>SystemHomePage</li></a>
		<a href="{% url 'phar_app:login' %}"><li>Pharmacy</li></a>
		<a href="{% url 'messages_inbox' %}"><li>Messages</li></a>
		<a href="{% url 'PatientSearch' %}" ><li>Search Patient</li></a>
		<a href="#"><li>Contact</li></a>
        <a href="{% url 'logout' %}"><li>Logout</li></a>
		
	</ul>
</div>
<br><br>
<form method='post'>
	{% csrf_token %}
<p>ward:<input type='text' name='ward'></p>
<p>room:<input type='text' name='room'></p>
<p>bed:<input type='text' name='bed'></p>
<input class="btn warning" type='submit' value="submit">
</form>


<div class="pattern"></div>
</body>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script type="text/javascript">
	$('div.btn').hoverIntent(function(){
		$(this).animate({"border-radius": "+=30px"},300);
	},function(){$(this).animate({"border-radius": "-=30px"},300);});
</script>
</html>

history_records/templates/medical_history/unit_summary_sheet.html
{% load staticfiles %}
<html>
<head>
	<title>CHMS | Medical File</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/general-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/medical.css' %}">
	
</head>
<body>
	<div class="header">
	<ul>
		<li class="brand"><img src="{% static 'logo.png' %}"></li>
		<a href="{% url 'SystemHomePage' %}"><li>SystemHomePage</li></a>
		<a href="{% url 'phar_app:login' %}"><li>Pharmacy</li></a>
		<a href="{% url 'messages_inbox' %}"><li>Messages</li></a>
		<a href="{% url 'PatientSearch' %}" ><li>Search Patient</li></a>
		<a href="#"><li>Contact</li></a>
        <a href="{% url 'logout' %}"><li>Logout</li></a>
		
	</ul>
</div>

	<h3>Unit Summary Sheet</h3>
	<h4>File No :</h4>
	<div class="sheet">
		
		<table>
            <tr class="green">
				<td>First Name : </td>
				<td> {{ patient.user.first_name }} </td>
			</tr>
			<tr class="green">
				<td>Last Name : </td>
				<td> {{ patient.user.last_name }} </td>
			</tr>
			<tr class="green">
					<td>Father Name : </td>
					<td> {{ patient.father_name }} </td>
			</tr>
			
				<tr class="green"><td>Sex:</td><td> {{ patient.get_gender_display }}</td></tr>
				<tr class="green"><td>Date of Birth:</td><td> {{ patient.birthday }}</td></tr>
				<tr class="green"><td>Occupation:</td><td> {{ patient.occupation }}</td></tr>
			
			
				<tr class="green"><td>Attending Physician:</td><td>{{ sheet.attending_physician.user.first_name}}{{sheet.attending_physician.user.last_name }}</td> </tr>
				<tr class="green"><td>Date of Addmition: </td><td>{{sheet.medical_file.date_of_addmition}}</td></tr>
				<tr class="green"><td>Date of Discharge:</td><td>{{sheet.medical_file.date_of_discharge}}</td></tr>
			
		
		
		<tr class="green"><td>Ward: </td><td>{{ sheet.medical_file.ward }}</td></tr>
		<tr class="green"><td>Room:</td><td> {{ sheet.medical_file.room }}</td></tr>
		<tr class="green"><td>Bed: </td><td>{{ sheet.medical_file.bed }}</td></tr>
		<tr class="green"><td>Address:</td><td>{{ patient.get_address_as_string }}</td></tr>
		<tr class="green"><td>Phone No.: </td><td>{{ patient.Tel }}</td></tr>
		
						<form method='post'>
				{% csrf_token %}
			<tr class="blue"><td>Chief Complaint of the Patient & Primary Diagnosis:</td><td><input name='ccapd' class='inp' type='text' value="{{ sheet.chief_complaint_and_primary_diagnosis }}" disabled='true'></td> </tr>
			<tr class="blue"><td>Final Diagnosis: </td><td><input class='inp' name="fd" type='text' value="{{ sheet.final_diagnosis }}" disabled='true'></td> </tr>
			<tr class="blue"><td>Medical & Surgical Procedures:</td><td><input name="masp" class='inp' type='text' value="{{ sheet.medical_and_surgical_procedures }}" disabled='true'></td> </tr>
			<tr class="blue"><td>Results of Paraclinical Examination:</td><td><input name="rope" class='inp' type='text' value="{{ sheet.results_of_paraclinical_examinations }}" disabled='true'></td> </tr>
			<tr class="blue"><td>Disease Progress (Cause of Death):</td><td><input name="dp" class='inp' type='text' value="{{ sheet.disease_progress }}" disabled='true'></td> </tr>
			<tr class="blue"><td>Patient's Condition on Discharge:</td><td><input name="pd" class='inp' type='text' value="{{ sheet.patient_condition_on_discharge }}" disabled='true'></td> </tr>
			<tr class="blue"><td>Recommendations after Discharge:</td><td><input name="ra" class='inp' type='text' value="{{ sheet.recommendations_after_discharge }}" disabled='true'></td> </tr>
			<tr class="blue"><td>Physician: </td><td>{{ sheet.attending_physician.user.first_name}} {{sheet.attending_physician.user.last_name }}</td></tr>
				</table>
			</div>{% ifequal type 6 %}

			          <input class="btn" type="submit" disabled id='submit' value="submit" disabled>
			    {% endifequal %}
			</form>
			{% ifequal type 6 %}
<div class="button-holder">
<button id="edit" class="btn warning"onclick="Edit()">Edit</button>
</div>
{% endifequal %}
		</div>

	</div>
		<script type="text/javascript">
		function Edit(){
			var list=	document.getElementsByClassName("inp");
			// console.log('salam');
			
			for (i=0;i<list.length;i++){
				list[i].disabled=false;
				// element.disabled=false;
			}
			var list=	document.getElementsByClassName("txtarea");
			// console.log('salam');
			
			for (i=0;i<list.length;i++){
				list[i].disabled=false;
				// element.disabled=false;
			}
			document.getElementById('submit').disabled=false;
		}
	</script>
<div class="pattern"></div>
	<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>

<script type="text/javascript">
	$('button.btn').hoverIntent(function(){
		$(this).animate({"border-radius": "+=30px"},300);
	},function(){$(this).animate({"border-radius": "-=30px"},300);});
	$('input.btn').hoverIntent(function(){
		$(this).animate({"border-radius": "+=30px"},300);
	},function(){$(this).animate({"border-radius": "-=30px"},300);});
	$('#edit').click(function(){
		// $('input[disabled]').removeAttr('disabled');
		$('input.btn').addClass('success');
		// $('textarea[disabled]').removeAttr('disabled');
	});
</script>

</body>
</html>