CHMS/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()
from CHMS import views

from django.conf import settings

# ... your normal urlpatterns here




urlpatterns = patterns('',

    url(r'hospital/$', include('hospital.urls')),
    url(r'pharmacy/', include('pharmacy.urls',namespace='phar_app')),
    url(r'history/', include('history_records.urls',namespace='history_records')),
    url(r'app/', include('androidApp.urls',namespace='android_app')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^patient/',include('patient.urls',namespace='patient_app')),
    url(r'^$', views.firstpage , name = 'firstpage'),
    url(r'^SystemHomePage/',views.SystemHomePage,name='SystemHomePage'),
    url(r'^PatientSearch/',views.PatientSearch,name='PatientSearch'),
    url(r'^rec/',include('Receptionist.urls', namespace='rec_app')),
    url(r'^login_all/',views.login,name='login_all'),
    url(r'^logout/',views.logout,name='logout'),
    url(r'^medicine/', include('medicine.urls',namespace='medicine_app')), # pharmacy
    url(r'^reports/',views.get_reports,name='reports'),
    url(r'^physician/',include('physician.urls',namespace='doc_app')),
    url(r'^messages/', include('django_messages.urls')),
    
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

medicine/urls.py
from django.conf.urls import patterns, url
from .views import medicine_list_view, MedicineDetailView, MedicineDeleteView
from .views import medicine_create_view, medicine_update_view,medicine_color_help


urlpatterns = patterns(
    '',
    url(r'^$', medicine_list_view, name='medicines-list'),
    url(r'colorHelp/$',medicine_color_help , name='color_help'),
    url(
        r'^create/$',
        medicine_create_view,
        name='medicines-create',
    ),
    url(
        r'^delete/(?P<code>[\w]+)/$',
        MedicineDeleteView.as_view(),
        name='medicines-delete',
    ),
    url(
        r'^update/(?P<code>[\w]+)/$',
        medicine_update_view,
        name='medicines-update',
    ),
    url(
        r'^(?P<code>[\w]+)/$',
        MedicineDetailView.as_view(),
        name='medicines-detail',
    ),
)

pharmacy/urls.py
__author__ = 'soheil'
from django.conf.urls import patterns, url
from pharmacy.views import login

urlpatterns = patterns('',

    url(r'^login/$', login, name='login'),

)

templates/PatientSearch.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>CHMS | SEARCH</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/general-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/search.css' %}">
</head>
<body>
<div class="header">
	<ul>
		<li class="brand"><img src="{% static 'logo.png' %}"></li>
		<a href="{% url 'login_all' %}"><li>Login</li></a>
		<a href="{% url 'phar_app:login' %}"><li>Pharmacy</li></a>
		<a href="{% url 'SystemHomePage' %}"><li>Home</li></a>
		<a href="#"><li>Contact</li></a>
		<a href="#"><li>About Us</li></a>
	</ul>
</div>
<div class="search">
		<h1 style="color:#34495e">Search Patient</h1>
		<p>Just type patient's name and click search button</p>
		    <form method="get" action="/PatientSearch/">
			Search: <input class="large" type="text" name="q" id="id_q" placeholder="search">
    		<input type="submit" value="Submit" name="submit_search_btn" class="btn  warning"  /> </select>
     		</form>
		
</div>
<div class="result">
	<table>
		<tr>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Age</th>
			<th>Hospital</th>
			<th>Hospital Tel</th>
		</tr>
	    {% for obj in found_entries %}
		<tr>
			<td>{{ obj.user.first_name }}</td>
			<td>{{ obj.user.last_name}}</td>
			<td>{{ obj.age}}</td>
            <td>{{ obj.parent_hospital.Hospital_Name}}</td>
            <td>{{ obj.parent_hospital.get_phone_numbers}}</td>
		</tr>
        {% endfor %}
	</table>
</div>
<div class="pattern"></div>
</body>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script type="text/javascript">
	$('input.btn').hoverIntent(function(){
		$(this).animate({"border-radius": "-=30px"},300);
	},function(){$(this).animate({"border-radius": "+=30px"},300);});
</script>
</html>

templates/SystemHomePage.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>CHMS | HomePage</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/general-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/homePage.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/responsiveslides.css' %}">
</head>
<body>
<div class="header">
	<ul>
		<li class="brand"><img src="{% static 'logo.png' %}"></li>
		<a href="{% url 'login_all' %}"><li>Login</li></a>
		<a href="{% url 'phar_app:login' %}"><li>Pharmacy</li></a>
		<a href="{% url 'PatientSearch' %}"><li>Patient Search</li></a>
		<a href="#"><li>Contact</li></a>
		<a href="#"><li>About Us</li></a>
	</ul>
</div>
<div class="slide">
	<ul class="rslides">
  <!-- <li><img src="{% static '1.jpg' %}" alt=""></li>
  <li><img src="{% static '2.jpg' %}" alt=""></li> -->
  <li><img src="{% static '3.jpg' %}" alt=""></li>
</ul>
</div>
<div class="content">
	<div class="sidebar">
		<ul>
			<li class="news">
			<h4>CHMS just Online</h4>
			<p>CHMS is finally online with
             Dozens of Capabilities Yet has to Come . You can Search For your Desired Patients in Just a Few Clicks.Wonder How ?</p>
			<a href="#"><div class="btn success">Read more</div></a>
			</li>
			<li class="news">
			<h4>CHMS Capabilites</h4>
			<p>The medical system has just own itself a unique integrated managing system , namely CHMS , No more pain does need to be felt for your medical treatment process ! </p>
			<a href="#"><div class="btn success">Read more</div></a>
			</li>
		</ul>
	</div>
	<div class="main">An efficient and future-proof Hospital Information System is a key component of a viable health system as Healthcare business models are evolving rapidly. Today, there is need to control processes that govern this sector as costs rise and there is a requirement to manage the information that health professionals need.
<br>
Hospital Management and Information System is a comprehensive solution that automates the clinical, electronic medical records (EMR), administrative and inventory functions, thereby leading to Improved operational effectiveness , Cost reductions and Improving quality of patient care</div>
</div>

</body>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script src="{% static 'js/responsiveslides.min.js' %}"></script>
<script>
	$('.header ul li').hoverIntent(function(){

	},function(){});

	$(".rslides").responsiveSlides({
  auto: true,             // Boolean: Animate automatically, true or false
  speed: 500,            // Integer: Speed of the transition, in milliseconds
  timeout: 4000,          // Integer: Time between slide transitions, in milliseconds
  pager: false,           // Boolean: Show pager, true or false
  nav: false,             // Boolean: Show navigation, true or false
  random: false,          // Boolean: Randomize the order of the slides, true or false
  pause: false,           // Boolean: Pause on hover, true or false
  pauseControls: true,    // Boolean: Pause when hovering controls, true or false
  prevText: "Previous",   // String: Text for the "previous" button
  nextText: "Next",       // String: Text for the "next" button
  maxwidth: "",           // Integer: Max-width of the slideshow, in pixels
  navContainer: "",       // Selector: Where controls should be appended to, default is after the 'ul'
  manualControls: "",     // Selector: Declare custom pager navigation
  namespace: "rslides",   // String: Change the default namespace used
  before: function(){},   // Function: Before callback
  after: function(){}     // Function: After callback
});
</script>
</html>

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title></title>
  <!-- Bootstrap -->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <!-- FontAwesome -->
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <!-- Navbar -->
  <link href="{% static 'css/navbar.css' %}" rel="stylesheet">
</head>

<body>

<head>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/" >

        </a>


       </div>
        </div>
  </nav>
</head>

<div class="container">
  {% block content %} 
  {% endblock content %}

</div>
  
{% block js %}
  <!-- Jquery -->
  <script src="{% static 'js/jquery.js' %}"></script>
  <!-- Bootstrap JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
{% endblock js %}

</body>

</html>

templates/create.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="panel panel-primary">

  <div class="panel-heading">
    <h1 class="panel-title">Add Medication <i class="fa fa-medkit"></i></h1>
  </div>

  <article class="panel-body">
    <form action="" method="post" role="form">
      {% csrf_token %}

      <div class="form-group">
        <label for="code">Code</label>
        <input name="code" id="code" type="text" class="form-control" required>
      </div>

      <div class="form-group">
        <label for="name">Name</label>
        <input name="name" id="name" type="text" class="form-control" required>
      </div>

      <div class="form-group">
        <label for="description">Description</label>
        <input name="description" id="description" type="text" class="form-control">
      </div>

      <div class="form-group">
        <label for="medicine_type">Type</label>
        <input name="medicine_type" id="medicine_type" type="text" class="form-control">
      </div>

      <div class="form-group">
        <label for="amount">amount</label>
        <input name="amount" id="amount" type="number" class="form-control" required>
      </div>

      <p>
        <button type="submit" class="btn btn-success btn-block"/> Create</button>
      </p>
    </form>

    <p>

    </p>
  </article>

{% endblock content %}

templates/delete.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="panel panel-danger">

  <div class="panel-heading">
    <h1 class="panel-title">
      Disposal of Medicines <strong>{{ object.code }} - {{ object.name|title }}</strong> <i class="fa fa-trash"></i>
    </h1>
  </div>

  <article class="panel-body">
    <form action="" method="post">
      {% csrf_token %}
      <h2>Are You Sure You Want To Delete The Drug <strong>{{ object.code }} - {{ object.name|title }}</strong>?</h2>
      <p>
        <button type="submit" class="btn btn-danger btn-block"/>Confirm</button>
      </p>
    </form>

    <section>
      <p>
        <a href="{% url 'medicine_app:medicines-list' %}" class="btn btn-success btn-block"> Back To List </a>
      </p>
      <p>
        <a href="{% url 'medicine_app:medicines-update' object.code %}" class="btn btn-primary btn-block"> Modify Medication </a>
      </p>
    </section>

  </article>

</div>

{% endblock content %}

templates/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="panel panel-primary">

  <div class="panel-heading">
    <h1 class="panel-title">
      Detail Medicine <i class="fa fa-medkit"></i>
    </h1>
  </div>

  <article class="panel-body">
    {% if object.code %}
      <p>Code: <strong>{{ object.code }}</strong></p>
    {% endif %}
    
    {% if object.name %}
      <p>name: <strong>{{ object.name|title }}</strong></p>
    {% endif %}
    
    {% if object.description %}
      <p>Description: <strong>{{ object.description }}</strong></p>
    {% endif %}
    
    {% if object.medicine_type %}
      <p>Type: <strong>{{ object.medicine_type|title }}</strong></p>
    {% endif %}

    {% if object.amount %}
      <p>amount: <strong>{{ object.amount }}</strong></p>
    {% endif %}
 
      <p>
        <a href="{% url 'medicine_app:medicines-list' %}" class="btn btn-success btn-block"> Back To List </a>
      </p>
    {% if user.is_superuser %}
      <p>
        <a href="{% url 'medicine_app:medicines-update' object.code %}" class="btn btn-primary btn-block"> modify Medication </a>
      </p>
      <p>
        <a href="{% url 'medicine_app:medicines-delete' object.code %}" class="btn btn-primary btn-block"> remove Medication </a>
      </p>
    {% endif %}
  </article>

</div>

{% endblock content %}

templates/firstpage.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>CHMS | Welcome</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/general-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/firstPage.css' %}">
</head>
<body>
		<div class="welcome">	
				<div class="logo">	<img src="{% static 'logo.png' %}"></div>
				<h4>Welcome To Comprehensive Hospitals Management System</h4>
		</div>
		<div class="buttons">
		<a href="{% url 'SystemHomePage' %}" ><div class="btn success large">System Homepage</div></a>
		<a href="{% url 'PatientSearch' %}" ><div class="btn warning large">Search Patient</div></a>
			</div>
			<div class="pattern"></div>
</body>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script>
	var heartRightMargin = window.innerWidth ;
	console.log(heartRightMargin);
	$('div.logo img').css('left',heartRightMargin/2 - 75);
	heartBeat();

	
	$('div.btn').hoverIntent(function(){
		dingDong($(this));
		// $(this).animate({"border-radius": "30px"},200);
	},function(){
		$(this).animate({"border-radius": "0px"},200);
	});

</script>
</html>

templates/list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

{% if not medicines %}
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    There are no drugs, <a href="{% url 'medicine_app:medicines-create' %}">Please Enter One</a>.
  </div>
{% endif %}

<div class="panel panel-primary">

  <div class="panel-heading">
    <h1 class="panel-title">List Of Medicines <i class="fa fa-medkit"></i></h1>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Code</th>
        <th>Name</th>
        <th>Type</th>
        <th>Amount</th>
      </tr>
    </thead>
    <tbody>
      {% for medicine in medicines %}
        <tr>
          <td><a href="{% url 'medicine_app:medicines-detail' medicine.code %}">{{ medicine.code }}</a></td>
          <td>{{ medicine.name }}</td>
          <td>{{ medicine.medicine_type }}</td>
          <td>{{ medicine.amount }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <article class="panel-body">
    <p>
      <a href="{% url 'medicine_app:medicines-create' %}" class="btn btn-success btn-block"> Add Medicine </a>
    </p>
  </article>

</div>

{% endblock content %}

templates/login_all.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>CHMS | LOGIN</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/general-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
<div class="header">
	<ul>
		<li class="brand"><img src="{% static 'logo.png' %}"></li>
		<a href="{% url 'SystemHomePage' %}"><li>Home</li></a>
		<a href="{% url 'phar_app:login' %}"><li>Pharmacy</li></a>
		<a href="#"><li>Hospitals</li></a>
		<a href="#"><li>Contact</li></a>
		<a href="#"><li>About Us</li></a>
	</ul>
</div>
	<div>
		<form name="login-form" action="/login_all/" method="POST">
			{% csrf_token %}
			<legend>Login</legend>
			<p class="fade">Fill the form below to login</p>
			<p><input   name="username" type="text" id="username"  placeholder="Username"></p>
			<p><input   name="password" type="password" id="password"  placeholder="Password"></p>
			<p><input type="submit" name="submit" class="btn warning " value="login"></p>
			<p class="error">{{ error}}</p>
		</form>
	</div>
	<div class="pattern"></div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script type="text/javascript">
	$('input.btn').hoverIntent(function(){
		$(this).animate({"border-radius": "+=30px"},300);
	},function(){$(this).animate({"border-radius": "-=30px"},300);});
</script>
</body>
</html>

templates/update.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="panel panel-primary">

  <div class="panel-heading">
    <h1 class="panel-title">modify Medication <i class="fa fa-medkit"></i></h1>
  </div>

  <article class="panel-body">
    <form action="" method="post" role="form">
      {% csrf_token %}

      <div class="form-group">
        <label for="code">Code</label>
        <input name="code" id="code" type="text" value="{{ medicine.code }}" class="form-control" readonly>
      </div>

      <div class="form-group">
        <label for="name">Name</label>
        <input name="name" id="name" type="text" value="{{ medicine.name }}" class="form-control" required>
      </div>

      <div class="form-group">
        <label for="description">Descrition</label>
        <input name="description" id="description" type="text" value="{{ medicine.description }}" class="form-control"name>
      </div>

      <div class="form-group">
        <label for="medicine_type">Type</label>
        <input name="medicine_type" id="medicine_type" type="text" value="{{ medicine.medicine_type }}" class="form-control">
      </div>

      <div class="form-group">
        <label for="amount">Amount</label>
        <input name="amount" id="amount" type="number" value="{{ medicine.amount }}" class="form-control" required>
      </div>

      <p>
        <button type="submit" class="btn btn-success btn-block"/>Modify</button>
      </p>
    </form>

    <section>
      <p>
        <a href="{% url 'medicine_app:medicines-list' %}" class="btn btn-primary btn-block"> Back To List </a>
      </p>
      <p>
        <a href="{% url 'medicine_app:medicines-delete' medicine.code %}" class="btn btn-primary btn-block"> Remove Medication </a>
      </p>
    </section>
  </article>
  
</div>

{% endblock content %}